"""add compliance checks

Revision ID: 7e7fd83eef8f
Revises: 554235165fa0
Create Date: 2026-08-29 12:25:29.305627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e7fd83eef8f'
down_revision: Union[str, Sequence[str], None] = '554235165fa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bid_submission_id', sa.Integer(), nullable=False),
    sa.Column('tender_requirement_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('checked_by', sa.String(length=100), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bid_submission_id'], ['bid_submissions.id'], ),
    sa.ForeignKeyConstraint(['tender_requirement_id'], ['tender_requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_checks_bid_submission_id'), 'compliance_checks', ['bid_submission_id'], unique=False)
    op.create_index(op.f('ix_compliance_checks_id'), 'compliance_checks', ['id'], unique=False)
    op.create_index(op.f('ix_compliance_checks_status'), 'compliance_checks', ['status'], unique=False)
    op.create_index(op.f('ix_compliance_checks_tender_requirement_id'), 'compliance_checks', ['tender_requirement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compliance_checks_tender_requirement_id'), table_name='compliance_checks')
    op.drop_index(op.f('ix_compliance_checks_status'), table_name='compliance_checks')
    op.drop_index(op.f('ix_compliance_checks_id'), table_name='compliance_checks')
    op.drop_index(op.f('ix_compliance_checks_bid_submission_id'), table_name='compliance_checks')
    op.drop_table('compliance_checks')
    # ### end Alembic commands ###
