"""add compliance assessments

Revision ID: 8b926d7141bf
Revises: 7e7fd83eef8f
Create Date: 2026-08-29 12:38:32.343007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b926d7141bf'
down_revision: Union[str, Sequence[str], None] = '7e7fd83eef8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bid_submission_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('assessment_metadata', sa.JSON(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bid_submission_id'], ['bid_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_assessments_bid_submission_id'), 'compliance_assessments', ['bid_submission_id'], unique=False)
    op.create_index(op.f('ix_compliance_assessments_id'), 'compliance_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_compliance_assessments_risk_level'), 'compliance_assessments', ['risk_level'], unique=False)
    op.create_index(op.f('ix_compliance_assessments_status'), 'compliance_assessments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compliance_assessments_status'), table_name='compliance_assessments')
    op.drop_index(op.f('ix_compliance_assessments_risk_level'), table_name='compliance_assessments')
    op.drop_index(op.f('ix_compliance_assessments_id'), table_name='compliance_assessments')
    op.drop_index(op.f('ix_compliance_assessments_bid_submission_id'), table_name='compliance_assessments')
    op.drop_table('compliance_assessments')
    # ### end Alembic commands ###
