"""add document extraction

Revision ID: b11558061421
Revises: d84f2f1fd19e
Create Date: 2026-08-29 08:01:03.373485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b11558061421'
down_revision: Union[str, Sequence[str], None] = 'd84f2f1fd19e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_extractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bid_document_id', sa.Integer(), nullable=False),
    sa.Column('extraction_status', sa.String(length=50), nullable=False),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('extractor_name', sa.String(length=100), nullable=True),
    sa.Column('extractor_version', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bid_document_id'], ['bid_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_extractions_bid_document_id'), 'document_extractions', ['bid_document_id'], unique=False)
    op.create_index(op.f('ix_document_extractions_extraction_status'), 'document_extractions', ['extraction_status'], unique=False)
    op.create_index(op.f('ix_document_extractions_id'), 'document_extractions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_extractions_id'), table_name='document_extractions')
    op.drop_index(op.f('ix_document_extractions_extraction_status'), table_name='document_extractions')
    op.drop_index(op.f('ix_document_extractions_bid_document_id'), table_name='document_extractions')
    op.drop_table('document_extractions')
    # ### end Alembic commands ###
