"""initial database schema

Revision ID: ef0257c7a9e2
Revises: 
Create Date: 2026-08-29 07:10:53.167783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef0257c7a9e2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bidders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('udyam_number', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bidders_gstin'), 'bidders', ['gstin'], unique=True)
    op.create_index(op.f('ix_bidders_id'), 'bidders', ['id'], unique=False)
    op.create_index(op.f('ix_bidders_pan'), 'bidders', ['pan'], unique=True)
    op.create_index(op.f('ix_bidders_udyam_number'), 'bidders', ['udyam_number'], unique=True)
    op.create_table('tenders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenders_id'), 'tenders', ['id'], unique=False)
    op.create_index(op.f('ix_tenders_reference_number'), 'tenders', ['reference_number'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('bid_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('bidder_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bidder_id'], ['bidders.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tender_id', 'bidder_id', name='uq_bid_submission_tender_bidder')
    )
    op.create_index(op.f('ix_bid_submissions_bidder_id'), 'bid_submissions', ['bidder_id'], unique=False)
    op.create_index(op.f('ix_bid_submissions_id'), 'bid_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_bid_submissions_tender_id'), 'bid_submissions', ['tender_id'], unique=False)
    op.create_table('tender_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('requirement_type', sa.String(length=100), nullable=False),
    sa.Column('requirement_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('validation_config', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_requirements_id'), 'tender_requirements', ['id'], unique=False)
    op.create_index(op.f('ix_tender_requirements_requirement_type'), 'tender_requirements', ['requirement_type'], unique=False)
    op.create_index(op.f('ix_tender_requirements_tender_id'), 'tender_requirements', ['tender_id'], unique=False)
    op.create_table('bid_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bid_submission_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bid_submission_id'], ['bid_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bid_documents_bid_submission_id'), 'bid_documents', ['bid_submission_id'], unique=False)
    op.create_index(op.f('ix_bid_documents_document_type'), 'bid_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_bid_documents_id'), 'bid_documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bid_documents_id'), table_name='bid_documents')
    op.drop_index(op.f('ix_bid_documents_document_type'), table_name='bid_documents')
    op.drop_index(op.f('ix_bid_documents_bid_submission_id'), table_name='bid_documents')
    op.drop_table('bid_documents')
    op.drop_index(op.f('ix_tender_requirements_tender_id'), table_name='tender_requirements')
    op.drop_index(op.f('ix_tender_requirements_requirement_type'), table_name='tender_requirements')
    op.drop_index(op.f('ix_tender_requirements_id'), table_name='tender_requirements')
    op.drop_table('tender_requirements')
    op.drop_index(op.f('ix_bid_submissions_tender_id'), table_name='bid_submissions')
    op.drop_index(op.f('ix_bid_submissions_id'), table_name='bid_submissions')
    op.drop_index(op.f('ix_bid_submissions_bidder_id'), table_name='bid_submissions')
    op.drop_table('bid_submissions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenders_reference_number'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_id'), table_name='tenders')
    op.drop_table('tenders')
    op.drop_index(op.f('ix_bidders_udyam_number'), table_name='bidders')
    op.drop_index(op.f('ix_bidders_pan'), table_name='bidders')
    op.drop_index(op.f('ix_bidders_id'), table_name='bidders')
    op.drop_index(op.f('ix_bidders_gstin'), table_name='bidders')
    op.drop_table('bidders')
    # ### end Alembic commands ###
